name: CI

on: push

jobs:
  unit_tests:
    name: checking
    runs-on: ubuntu-latest
    container:
      image: jjmerelo/raku-test:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: gtest
        run: make check
    
